### ISSUE TITLE
Create new release instead of updating the old one 

### ISSUE THREAD

**Issue by hax4dazy** [mrdude2478/TinWoo#42]
Instead of updating the old release constantly, create a new release every time you update / change something.

**Comment by mrdude2478** [comment]
No

**Comment by hax4dazy** [comment]
Could you at least explain why? It would make using GitHub a lot easier for other users if they saw that the latest release wasn't in 2020

**Comment by mrdude2478** [comment]
Tinwoo tells you there's a release if you click on check for update, and I can easily see when I updated stuff without needing to scroll down to lots of different releases. Also this is my own personal git so I'll do what I want with it. I am only sharing the code mods because I am a kind hearted soul and so that you can download and build yourself or check the code for bugs. As for the releases, the only reason I even have a release page is because tinwoo checks that in the json format of that page to see if there's an update or not - or it would not exist.

**Comment by hax4dazy** [comment]
I know that tinwoo tells you whenever there is a release but that won't work if users haven't downloaded the homebrew in the first place. Seeing as your app isn't on the homebrew app store users WILL have to come to GitHub only to download the latest release. Ontop of that making a new release makes it so that GitHub automatically archives the code that was used to make that build, basically making it so that anyone can download that specific code archive and build it to get the exact same result. Plus it allows you to add a version number to every release so users can quickly and easily identify whenever they have an outdated release.

**Comment by mrdude2478** [comment]
If you want old code, you can get it here:
https://github.com/mrdude2478/TinWoo/tags

**Comment by hax4dazy** [comment]
So you do use tags but refuse to use the release system? Bruh
